<?php
// $Id$
/**
 * @file mukurtu_splash.module
 * Displays a block of configuration links in a Colorbox popup.
 */

/**
 * Implementation of hook_menu().
 */
function mukurtu_splash_menu() { 
  $items['splash/%mukurtu_splash_block'] = array(
    'title' => '',
    'page callback' => 'mukurtu_splash_block_display',
    'page arguments' => array(1),
    'access callback' => TRUE, 
  );

  return $items;
}


/**
 * Implementation of hook_init().
 */
function mukurtu_splash_init() {

  // Logged out users
/*
  if(drupal_is_front_page() 
      && !user_access('administer site configuration')
      && !isset($_COOKIE['prealpha_seen'])
      && !user_is_logged_in() 
      ){

    setcookie('prealpha_seen', "seen", time + 3600 * 24 * 180);
  
    $url = url('splash/site_prealpha');
        
    $js = 'jQuery(document).ready(function () { jQuery.colorbox({ ';
    $js .= 'href: "' . $url . '",';
    $js .= 'width: 800,';
    $js .= 'height: 550,';
    $js .= 'opacity: .6,';
    $js .= '});});';
    
    drupal_add_js(drupal_get_path('module', 'mukurtu_splash') . '/mukurtu_splash.js');
    drupal_add_js($js, array('type' => 'inline', 'group' => JS_THEME, 'every_page' => TRUE)); 
  }
*/



  // Admin splash screens.

  // Config Site
/*
  if (drupal_is_front_page() 
      && user_access('administer site configuration')

      && !variable_get('mukurtu_splash_config_seen', FALSE)
      ) {
 
    variable_set('mukurtu_splash_config_seen', TRUE); 
    
    $url = url('splash/site_config');
        
    $js = 'jQuery(document).ready(function () { jQuery.colorbox({ ';
    $js .= 'href: "' . $url . '",';
    $js .= 'width: 800,';
    $js .= 'height: 480,';
    $js .= 'opacity: .6,';
    $js .= '});});';
    
    drupal_add_js(drupal_get_path('module', 'mukurtu_splash') . '/mukurtu_splash.js');
    drupal_add_js($js, array('type' => 'inline', 'group' => JS_THEME, 'every_page' => TRUE)); 
  }  
*/
/*
  
  // Site configured admin welcome screen
  if (drupal_is_front_page() 
      && user_access('administer site configuration')
      && !variable_get('mukurtu_splash_welcome_seen', FALSE)
      ) {

    $url = url('splash/site_welcome');

    $js = 'jQuery(document).ready(function () { jQuery.colorbox({ ';
    $js .= 'href: "' . $url . '",';
    $js .= 'width: 600,';
    $js .= 'height: 400,';
    $js .= 'opacity: .6,';
    $js .= '});});';
    drupal_add_js(drupal_get_path('module', 'mukurtu_splash') . '/mukurtu_splash.js');
    drupal_add_js($js, array('type' => 'inline', 'group' => JS_THEME, 'every_page' => TRUE)); 
    
    // This makes it so that the splash page will never show up again, unless
    // this variable is set back to FALSE.
    variable_set('mukurtu_splash_welcome_seen', TRUE);
  }
  
  $mod_uri = drupal_get_path('module', 'mukurtu_splash');
  drupal_add_css( $mod_uri . '/mukurtu_splash.css');
*/
}

/**
 * Implementation of hook_block_info().
 */
function mukurtu_splash_block_info() {
  $blocks['site_welcome'] = array(
    'info' => t('Welcome message splash screen'),
  );

  $blocks['site_prealpha'] = array(
    'info' => t('Alpha Site Notice'),
  );
  $blocks['site_start'] = array(
    'info' => t('Mukurtu Dashboard: Site Start'),
  );
  $blocks['demo_config'] = array(
    'info' => t('Mukurtu Dashboard: Add Demo Content'),
  );
  $blocks['site_config'] = array(
    'info' => t('Mukurtu Dashboard: Configure Mukurtu'),
  );
  $blocks['manage_content'] = array(
    'info' => t('Mukurtu Dashboard: Manage Content'),
  );
  $blocks['manage_community'] = array(
    'info' => t('Mukurtu Dashboard: Manage Communities'),
  );
  $blocks['support'] = array(
    'info' => t('Mukurtu Dashboard: Support'),
  );
  $blocks['user'] = array(
    'info' => t('Mukurtu Dashboard: User'),
  );
  return $blocks;
}


/**
 * Implementation of hook_block_view().
 */
function mukurtu_splash_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'site_welcome':
      $block['subject'] = t('You have successfully installed Mukurtu.');
      $block['content'] = mukurtu_splash_block_site_welcome();
      break;
    case 'site_prealpha':
/*       $block['subject'] = '<h1>' .t('Alpha!') . '</h1>'; */
      $block['content'] = mukurtu_splash_block_site_prealpha();
      break;
    case 'site_start':
      $block['subject'] = t('Set up Site');
      $block['content'] = mukurtu_splash_block_site_start();
      break;
    case 'demo_config':
      $block['subject'] = t('Mukurtu Demo Content');
      $block['content'] = mukurtu_splash_block_demo_config();
      break;
    case 'site_config':
      $block['subject'] = t('Mukurtu Configuration');
      $block['content'] = mukurtu_splash_block_site_config();
      break;
    case 'manage_content':
      $block['subject'] = t('Manage Content');
      $block['content'] = mukurtu_splash_block_manage_content();
      break;
    case 'manage_community':
      $block['subject'] = t('Manage Communities');
      $block['content'] = mukurtu_splash_block_manage_community();
      break;
    case 'support':
      $block['subject'] = t('Support');
      $block['content'] = mukurtu_splash_block_support();
      break;
    case 'user':
      $block['subject'] = t('My account');
      $block['content'] = mukurtu_splash_block_user();
      break;
  }
  return $block;
}

/**
 * Loader function for hook_menu().
 */
function mukurtu_splash_block_load($delta) {
  return block_load('mukurtu_splash', $delta);
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_site_prealpha() {
  $output .= '<h1>' . variable_get('mukurtu_city_name') . '</h1>';
  $output .= '<img src="' . base_path() . path_to_theme() . '/images/mukurtu_alpha.png" alt="Mukurtu Alpha" />';
  $output .= '<p>' . t('This is a new site, we are understanding how best to make the site useful to you.') . '</p>';
  $output .= '<p>' . t('We are inviting folks to test the site and add information to it. [Link]');

  $block = array(
    '#markup' => $output,
  );
  return $block;

}
/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_site_welcome() {
  $markup = '';
  $markup .= '<p><strong>'. t('Next:') . '</strong>' . t('Setup your site. Go to the !dashboard.', array('!dashboard' => l(t('Dashboard'), 'admin/dashboard', array('attributes' => array('class' => array('mukurtu-splash-link')))))) . '</p>';
/*   $markup .= '<p>' . t('Tell us what you think, or better yet, !contribute to make it even better.', array('!contribute' => l(t('contribute to Mukurtu'), 'http://mukurtu.org/'))) . '</p>'; */

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_site_start() {

  $items = array();

  $markup = '';

  $items[] = array (
    'title' => 'Change site name, slogan and email address.',
    'href' => 'admin/config/system/site-information',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Shortcut to page where you can change some settings for this site. The site name, a slogan for your site, and the email address for the site administrator.'),
  );

  $items[] = array (
    'title' => 'Change Logo (Homepage & Browse)',
    'href' => 'admin/appearance/delta/list/browse/configure',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Shortcut to theme settings where you can change your logo.'),
  );

  $items[] = array (
    'title' => 'Change Logo (All other site pages)',
    'href' => 'admin/appearance/settings/mukurtu_theme',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Shortcut to theme settings where you can change your logo.'),
  );

  $items[] = array (
    'title' => 'View & Edit About page',
    'href' => 'about',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Mukurtu comes with a default about page that you can edit.'),
  );

  $items[] = array (
    'title' => 'Enable and disable extra menu items',
    'href' => 'admin/structure/menu/manage/main-menu',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Mukurtu comes with additional pages that you can enable.'),
  );
  
  $items[] = array (
    'title' => 'Create a single-page frontpage app.',
    'href' => 'admin/config/frontpage_app',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Lives at /frontpage_app; Set to front page on Site Information to use this page as your frontpage.'),
  );

  $items[] = array (
    'title' => 'Edit Custom Site Header',
    'href' => 'admin/structure/block/manage/boxes/ma_site_header/configure',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Edit HTML markup of Custom Site Header'),
  );

  $items[] = array (
    'title' => 'Edit Custom Site Footer',
    'href' => 'admin/structure/block/manage/boxes/ma_site_footer/configure',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Edit HTML markup of Custom Site Footer'),
  );
  

  	
  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}


/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_site_config() {

  $items = array();

  $markup = '';

  $items[] = array (
    'title' => 'Set Private File Path',
    'href' => 'admin/config/media/file-system',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Drupal requires you to set the path to the private folder in the file system.'),
  );

  $items[] = array (
    'title' => 'Configure Google Analytics',
    'href' => 'admin/config/system/googleanalytics',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('You will need to create a Google Analytics account and then configure Google Analytics on this site.'),
  );

  $items[] = array (
    'title' => 'Configure Mollom',
    'href' => 'admin/config/content/mollom/settings',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Configure Mollom. Requires an account.'),
  );

  $items[] = array (
    'title' => 'Rebuild Site Permissions',
    'href' => 'admin/reports/status/rebuild',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('If doing a lot of site content editing, you may need to rebuild permissions to make sure that access permissions remain set correctly.'),
  );

  $items[] = array (
    'title' => 'Make Search Work (Run Cron to build Search Index)',
    'href' => 'admin/reports/status/run-cron ',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('If you are not getting search results, your site content has probably not been indexed. Search will update if you run cron. See if all content is indexed in search: admin/config/search/settings'),
  );
  
  	
  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_manage_content() {

  $items = array();

  $markup = '';

  $items[] = array (
    'title' => 'Manage Content',
    'href' => 'admin/content',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('View all content on the site'),
  );

  $items[] = array (
    'title' => 'Manage Comments',
    'href' => 'admin/content/comment',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('View all comments'),
  );

  $items[] = array (
    'title' => 'View Media',
    'href' => 'admin/content/file',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('View media files.'),
  );

  $items[] = array (
    'title' => 'Add Media',
    'href' => 'file/add',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch add media files.'),
  );

  $items[] = array (
    'title' => 'Add One Category',
    'href' => 'admin/structure/taxonomy/category/add',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Add a Category'),
  );

  $items[] = array (
    'title' => 'Import Many Categories',
    'href' => 'import/import_categories',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many categories from CSV file. Import Media first.'),
  );

  $items[] = array (
    'title' => 'Add One Digital Heritage',
    'href' => 'node/add/digital-heritage',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Add a Digital Hertiage Item.'),
  );

  $items[] = array (
    'title' => 'Import Digital Heritage Metadata',
    'href' => 'import/digital_heritage_metadata',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many digital heritage items from CSV file. Import Media first.'),
  );
  
  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_demo_config() {

  $items = array();

  $markup = '';

  $items[] = array (
    'title' => 'Download Sample Content',
    'href' => 'https://github.com/codamatic/mukurtu-demo-content/zipball/master',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('100MB of Demo Content. Download from Github: https://github.com/codamatic/mukurtu-demo-content'),
  );
  
  $items[] = array (
    'title' => '1. Add Media',
    'href' => 'file/add',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch add media files.'),
  );

  $items[] = array (
    'title' => '2. Import Many Cultural Protocols',
    'href' => 'import/import_cultural_protocols',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many cultural protocols from CSV file.  Import Media first.'),
  );

  $items[] = array (
    'title' => '3. Import Many Communities',
    'href' => 'import/import_communities',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many communities from CSV file. Import Media first.'),
  );

  $items[] = array (
    'title' => '4. Add Many Users',
    'href' => 'import/import_users',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many users from CSV file'),
  );

  $items[] = array (
    'title' => '5. Import Many Categories',
    'href' => 'import/import_categories',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many categories from CSV file. Import Media first.'),
  );

  $items[] = array (
    'title' => '6. Import Digital Heritage Metadata',
    'href' => 'import/digital_heritage_metadata',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many digital heritage items from CSV file. Import Media first.'),
  );
  
  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;  
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_manage_community() {

  $items = array();

  $markup = '';


  $items[] = array (
    'title' => 'View Users',
    'href' => 'admin/people',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('View people with accounts.'),
  );

  $items[] = array (
    'title' => 'Add User',
    'href' => 'admin/people/create',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Create an account for a user.'),
  );
  $items[] = array (
    'title' => 'Add Many Users',
    'href' => 'import/import_users',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many users from CSV file'),
  );

  $items[] = array (
    'title' => 'View All Groups',
    'href' => 'group-list',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('View all groups'),
  ); 



  $items[] = array (
    'title' => 'Add One Community',
    'href' => 'node/add/community',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Add a Community'),
  );

  $items[] = array (
    'title' => 'Import Many Communities',
    'href' => 'import/import_communities',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many communities from CSV file. Import Media first.'),
  );

  $items[] = array (
    'title' => 'View Communities',
    'href' => 'communities',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('See all Community Groups'),
  ); 

  $items[] = array (
    'title' => 'Add One Cultural Protocol',
    'href' => 'node/add/cultural-protocol-group',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Add a Cultural Protocol.'),
  );

  $items[] = array (
    'title' => 'Import Many Cultural Protocols',
    'href' => 'import/import_cultural_protocols',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('Batch import many cultural protocols from CSV file.  Import Media first.'),
  );

  $items[] = array (
    'title' => 'View Cultural Protocols',
    'href' => 'cultural-protocols',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
    'description' => t('See all Cultural Protocol Groups'),
  );  

  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}

/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_support() {

  $items = array();

  $markup = '';

  $items[] = array (
    'title' => 'Mukurtu Wiki',
    'href' => 'http://www.mukurtu.org/wiki/Main_Page',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
  );

  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}


/**
 * Helper function to assemble the initial site configuration block.
 */
function mukurtu_splash_block_user() {

  $items = array();

  $markup = '';

  global $user;

  $items[] = array (
    'title' => 'My account',
    'href' => 'user/' . $user->uid . '/edit',
    'localized_options' => array('attributes' => array('class' => array('opic-dashboard-content'))),    
  );


  $content = array ('content' => $items);
  $markup = theme('admin_block_content', $content);

  $block = array(
    '#markup' => $markup,
  );
  return $block;
}

/**
 * Implementation of hook_block_display().
 */
function mukurtu_splash_block_display($block) {
  $GLOBALS['devel_shutdown'] = FALSE; // Prevent devel module from spewing.
  
  $renderable_block = _block_get_renderable_array(_block_render_blocks(array($block)));
  print render($renderable_block);

  exit;
}

/**
 * Helper function to determine if all the tasks related to initial site configuration
 * have either been completed or dismissed.
 * TODO: Create a checklist of completed/dismissed tasks.
 * TODO: Check that list here.
 */
function mukurtu_splash_site_welcome_check() {
  return TRUE;
}

/**
 * Menu callback function to help toggle the demo content module's status.
 */
function mukurtu_splash_toggle_demo_content() {
  drupal_goto('admin/dashboard');
}
