<?php

/**
 * Implementation of hook_menu()
 */
function mukurtu_frontpage_menu() {
  $items['frontpage_app'] = array(
    'title' => t('Mukurtu'),
    'description' => t(''),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'page callback' => 'mukurtu_frontpage_content',
  );

  $items['admin/config/frontpage_app'] = array(
    'title' => 'Mukurtu FrontPage',
    'description' => 'Frontpage content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mukurtu_frontpage_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;	  
}

function mukurtu_frontpage_content_load() {

  // @TODO add drupal site path for default.
  $default_content = array( 
    'sections' => array(
      0 => array(
        'title' => t(''),
        'anchor' => 'header',
        'detail' => '',
        'jsondata' => '',
        'content' => '<div class="video"><iframe width="560" height="315" src="http://www.youtube.com/embed/rsk_j7kPlz0" frameborder="0" allowfullscreen></iframe></div><div class="intro">The free, mobile and open source platform built for indigenous communities to manage and share digital cultural heritage.</div>',
        ),
      1 => array(
        'title' => 'Vision',
        'anchor' => 'vision',
        'link' => 'about',
        'detail' => 'An indigenous CMS',
        'content' => '<div class="tab-content">
          <div class="tab"><h3>Label</h3><p>Content</p></div>
          <div class="tab"><h3>Label</h3><p>Content</p></div>
        </div>',      
        'jsondata' => '',
        'display' => TRUE,
        ),
      2 => array(
        'title' => 'Features',
        'anchor' => 'features',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => 'http://mukurtu.local/app/views/ma_browse.json?&display_id=page_app&keys=&label[Sample+Cultural+Protocol]=Sample+Cultural+Protocol&promote=All',
        'display' => TRUE,
        ),  
      3 => array(
        'title' => 'Features',
        'anchor' => 'features',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => 'http://mukurtu.local/app/views/ma_browse.json?&display_id=page_app&keys=&label[Sample+Cultural+Protocol]=Sample+Cultural+Protocol&promote=All',
        'display' => TRUE,
        ),  
      4 => array(
        'title' => 'Communities',
        'anchor' => 'communities',
        'link' => 'communities',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => 'http://mukurtu.local/app/views/communities.json?&display_id=communities',
        'display' => TRUE,
        ),   
      5 => array(
        'title' => 'Contact',
        'anchor' => 'contact',
        'link' => 'contact',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'display' => TRUE,
        'jsondata' => '',
        ),    
      6 => array(
        'title' => 'Support',
        'anchor' => 'support',
        'link' => 'support',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'display' => TRUE,
        'jsondata' => '',
        ),
      7 => array(
        'title' => '',
        'anchor' => 'footer',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => '',
        'display' => TRUE,
        ),
    )
  );

  // Load content saved in database if it exists.
  $content = variable_get('mukurtu_frontpage_settings', $default_content);
  return $content;
}









/**
 * General configuration form for controlling the colorbox behaviour.
 */
function mukurtu_frontpage_settings() {

  $db_fields = mukurtu_frontpage_content_load();
  
  $form['mukurtu_frontpage_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Mukurtu Frontpage settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );

  $form['mukurtu_frontpage_settings']['sections'] = array(
    '#type' => 'fieldset',
    '#title' => t('Sections'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  for($i=0; $i < count($db_fields['sections']); $i++) {

    $form['mukurtu_frontpage_settings']['sections'][$i] = array(
      '#type' => 'fieldset',
      '#title' => $db_fields['sections'][$i]['title'],
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#default_value' => $db_fields['sections'][$i]['title'],
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['anchor'] = array(
      '#type' => 'textfield',
      '#title' => t('Anchor'),
      '#default_value' => $db_fields['sections'][$i]['anchor'],
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['detail'] = array(
      '#type' => 'textarea',
      '#title' => t('Detail'),
      '#default_value' => $db_fields['sections'][$i]['detail'],
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['content'] = array(
      '#type' => 'textarea',
      '#title' => t('Markup'),
      '#default_value' => $db_fields['sections'][$i]['content'],
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['jsondata'] = array(
      '#type' => 'textarea',
      '#title' => t('JSON Data'),
      '#default_value' => $db_fields['sections'][$i]['jsondata'],
    );      

    $form['mukurtu_frontpage_settings']['sections'][$i]['blockname'] = array(
      '#type' => 'textfield',
      '#title' => t('BlockName'),
      '#default_value' => $db_fields['sections'][$i]['blockname'],
    ); 

    $form['mukurtu_frontpage_settings']['sections'][$i]['display'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display this section'),
      '#default_value' => $db_fields['sections'][$i]['display'],
    ); 

  }

  return system_settings_form($form);
}


// @TODO Add an extra section dynamically.
// ?? - http://drupal.org/node/331941

/** 
 * Submit handler for the "Add Tab" button.
 */ 
/*
function mukurtu_frontpage_settings_submit($form, &$form_state) {
  unset($form_state['submit_handlers']);
  form_execute_handlers('submit', $form, $form_state);
  $mukurtu_frontpage_values = $form_state['values'];
  $form_state['mukurtu_frontpage_settings'] = $mukurtu_frontpage_values;
  $form_state['rebuild'] = TRUE;


  if ($form_state['values']['sections']) {
    $form_state['section_count'] = count($form_state['values']['mukurtu_frontpage_sections']) + 1;
  }

  return $mukurtu_frontpage_values;
}
*/

/** 
 * AHAH callback.
 */ 
/*
function mukurtu_frontpage_ahah() {
  $form_state = array('storage' => NULL, 'rebuild' => TRUE);
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form['#post'] = $_POST;
  $form['#redirect'] = FALSE;
  $form['#programmed'] = FALSE;
  $form_state['post'] = $_POST;
  drupal_process_form($form_id, $form, $form_state);
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);
  $mukurtu_frontpage_form = $form['mukurtu_frontpage_settings']['mukurtu_frontpage_sections'];
  unset($mukurtu_frontpage_form['#prefix'], $mukurtu_frontpage_form['#suffix']); // Prevent duplicate wrappers.
  $javascript = drupal_add_js(NULL, NULL, 'header');
  drupal_json(array(
    'status'   => TRUE,
    'data'     => theme('status_messages') . drupal_render($mukurtu_frontpage_form),
    'settings' => call_user_func_array('array_merge_recursive', $javascript['setting']),
  ));
}
*/

function mukurtu_frontpage_content() {

  global $base_url;
  $output = '';
  
  return $output;
}

// A lightweight frontpage singlepage app - with a little bit of database integration for content-editing purposes.
function mukurtu_frontpage_preprocess_page(&$vars){
  if($vars['is_front']) {
 
    global $base_path;
    drupal_add_js(array('mukurtu_frontpage' => array('menu_element' => variable_get('mukurtu_frontpage_menu', '#main-menu'), 'base_path' => $base_path)), 'setting');
    drupal_add_js(drupal_get_path('module', 'mukurtu_frontpage') . '/js/mukurtu_frontpage.js');


    if (module_exists('libraries')) {
      $underscore_path = libraries_get_path('underscore');
      drupal_add_js($underscore_path . '/underscore-min.js');
  
   //   $jquery_path = libraries_get_path('jquery-1.8.2');
   //   drupal_add_js($jquery_path . '/jquery-1.8.2.min.js');
  
  
      $bootstrap_path = libraries_get_path('bootstrap');
      drupal_add_js($bootstrap_path . '/js/bootstrap.js');
      drupal_add_css($bootstrap_path . '/css/bootstrap.css');
      drupal_add_css(drupal_get_path('module', 'jcarousel') . '/skins/default/jcarousel-default.css');

      drupal_add_js(drupal_get_path('module', 'jcarousel') . '/js/jquery.jcarousel.min.js');


    }
  
    $vars['frontpage'] = array();
  
    // Menu
    // @TODO load menu items from list form -- the title, shortname, detail and html (4 fields each) == 5 if using views json parser -- have the json fields named a certain way in views:  title image description link
    // We are not using the menu system, it is overkill.
    
    // @TODO build off page items.
    
    
  
    
    // @TODO these will be linked to a form -- and will be able to add some more as necessary. Hard-coding for now.
    $vars['frontpage']['page_items'] = mukurtu_frontpage_content_load();
  
  
    $menu_items = array();
    foreach($vars['frontpage']['page_items']['sections'] as $item) {    

      if($item['jsondata']) {      
        $json_path = $item['jsondata'];
        
        drupal_add_js('mukurtu_frontpage.query("' . $json_path . '", mukurtu_frontpage.loadData, "' . $item['anchor'] .'")',  array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
      }
      $i++;
    }
 
  }
}

