<?php
define('MUKURTU_FRONTPAGE', drupal_get_path('module', 'my_module'));

/**
 * Implementation of hook_menu()
 */
function mukurtu_frontpage_menu() {
  $items['frontpage_app'] = array(
    'title' => t('Mukurtu'),
    'description' => t(''),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'page callback' => 'mukurtu_frontpage_content',
  );

  $items['admin/config/frontpage_app'] = array(
    'title' => 'Mukurtu FrontPage Settings',
    'description' => 'Configure front page content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mukurtu_frontpage_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;	  
}

function mukurtu_frontpage_content_load() {

  // @TODO add drupal site path for default.
  $default_content = array( 
    'header' => TRUE,
    'footer' => TRUE,
    'sections' => array(
      0 => array(
        'title' => t(''),
        'anchor' => 'header',
        'detail' => '',
        'jsondata' => '',
        'content' => '<div class="video"><iframe width="560" height="315" src="http://www.youtube.com/embed/rsk_j7kPlz0" frameborder="0" allowfullscreen></iframe></div><div class="intro">The free, mobile and open source platform built for indigenous communities to manage and share digital cultural heritage.</div>',
        ),
      1 => array(
        'title' => 'Vision',
        'anchor' => 'vision',
        'link' => 'about',
        'detail' => 'An indigenous CMS',
        'content' => '<div class="tab-content">
          <div class="tab"><h3>Label</h3><p>Content</p></div>
          <div class="tab"><h3>Label</h3><p>Content</p></div>
        </div>',      
        'jsondata' => '',
        'display' => TRUE,
        ),
      2 => array(
        'title' => 'Features',
        'anchor' => 'features',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => 'http://mukurtu.local/app/views/ma_browse.json?&display_id=page_app&keys=&label[Sample+Cultural+Protocol]=Sample+Cultural+Protocol&promote=All',
        'display' => TRUE,
        ),  
      3 => array(
        'title' => 'Features',
        'anchor' => 'features',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => 'http://mukurtu.local/app/views/ma_browse.json?&display_id=page_app&keys=&label[Sample+Cultural+Protocol]=Sample+Cultural+Protocol&promote=All',
        'display' => TRUE,
        ),  
      4 => array(
        'title' => 'Communities',
        'anchor' => 'communities',
        'link' => 'communities',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => 'http://mukurtu.local/app/views/communities.json?&display_id=communities',
        'display' => TRUE,
        ),   
      5 => array(
        'title' => 'Contact',
        'anchor' => 'contact',
        'link' => 'contact',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'display' => TRUE,
        'jsondata' => '',
        ),    
      6 => array(
        'title' => 'Support',
        'anchor' => 'support',
        'link' => 'support',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'display' => TRUE,
        'jsondata' => '',
        ),
      7 => array(
        'title' => '',
        'anchor' => 'footer',
        'detail' => 'blasdf asdf asdfasd fasdf a.',
        'content' => 'content asdf adsf asdf asd fasd.',
        'jsondata' => '',
        'display' => TRUE,
        ),
    )
  );

  // Load content saved in database if it exists.
  $content = variable_get('mukurtu_frontpage_settings', $default_content);
  return $content;
}

/**
 * General configuration form for controlling the colorbox behaviour.
 */
function mukurtu_frontpage_settings() {

  $db_fields = mukurtu_frontpage_content_load();
  
  $form['mukurtu_frontpage_settings'] = array(
    '#type' => 'fieldset',
/*     '#title' => '<h3>' . t('Configure front page sections') . '</h3>', */
    '#collapsible' => FALSE,
    '#description' => t('Add content, menu items and other elements for the frontpage single-page site brochure.'),
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );

  $form['mukurtu_frontpage_settings']['header'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Custom Site Header'),
    '#description' => l('Edit Custom Site Header', 'admin/structure/block/manage/boxes/ma_site_header/configure') . '. <br />' . t(' Include a site-wide header from the Custom Header Block.') . '</p>',
    '#default_value' => $db_fields['header'],
  );

  $form['mukurtu_frontpage_settings']['sections'] = array(
    '#type' => 'fieldset',
/*     '#title' => t('Sections'), */
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  for($i=0; $i < count($db_fields['sections']); $i++) {

    $form['mukurtu_frontpage_settings']['sections'][$i] = array(
      '#type' => 'fieldset',
      '#title' => t('Section') . ' ' . $db_fields['sections'][$i]['title'],
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#description' => t('Add content for this section.'),
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['display'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display this section'),
      '#default_value' => $db_fields['sections'][$i]['display'],
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#default_value' => $db_fields['sections'][$i]['title'],
      '#description' => t('Enter title for this section. Leave blank to exclude the title.'),
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['anchor'] = array(
      '#type' => 'textfield',
      '#title' => t('HTML Anchor'),
      '#default_value' => $db_fields['sections'][$i]['anchor'],
      '#description' => t('Short name for the section. Should be all lowercase letters with no spaces. Use an underscore (_) as a spacer.'),
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['detail'] = array(
      '#type' => 'textarea',
      '#title' => t('Description'),
      '#default_value' => $db_fields['sections'][$i]['detail'],
      '#description' => t('Short description for this section.'),
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['content'] = array(
      '#type' => 'textarea',
      '#title' => t('Markup'),
      '#default_value' => $db_fields['sections'][$i]['content'],
      '#description' => t('<p>Enter HTML markup for this section.</p><ul><li>Use good judgement with your HTML.</li><li>This section works with <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> markup. You can add tabs, content dropdowns and more.'),
    );

    $form['mukurtu_frontpage_settings']['sections'][$i]['jsondata'] = array(
      '#type' => 'textarea',
      '#title' => t('JSON Data URL'),
      '#default_value' => $db_fields['sections'][$i]['jsondata'],
      '#description' => t('Enter JSON data url. This can come from the Browse view, or Communities or other Services enabled views. Allowed fields are <em>title</em>, <em>description</em>, <em>image</em>, <em>content</em>.'),
    );      

    $form['mukurtu_frontpage_settings']['sections'][$i]['blockname'] = array(
      '#type' => 'textfield',
      '#title' => t('Block Name'),
      '#default_value' => $db_fields['sections'][$i]['blockname'],
      '#description' => t('Enter the machine name for the block to include'),
    ); 
    
    if ($i == count($db_fields['sections']) - 1) {
      $form['mukurtu_frontpage_settings']['sections'][$i]['#description'] =
       t('Final Section. Use title <em>footer</em> to use default styles. Rename footer to use your own markup.');
    }
    

  }
  

  $form['mukurtu_frontpage_settings']['footer'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Custom Site Footer'),
    '#description' => l('Edit Custom Site Footer', 'admin/structure/block/manage/boxes/ma_site_footer/configure') . '.' . t(' Include a site-wide custom footer from the Custom Footer Block'),
    '#default_value' => $db_fields['footer'],
    
  );

  return system_settings_form($form);
}


// @TODO Add an extra section dynamically.
// ?? - http://drupal.org/node/331941

/** 
 * Submit handler for the "Add Tab" button.
 */ 
/*
function mukurtu_frontpage_settings_submit($form, &$form_state) {
  unset($form_state['submit_handlers']);
  form_execute_handlers('submit', $form, $form_state);
  $mukurtu_frontpage_values = $form_state['values'];
  $form_state['mukurtu_frontpage_settings'] = $mukurtu_frontpage_values;
  $form_state['rebuild'] = TRUE;


  if ($form_state['values']['sections']) {
    $form_state['section_count'] = count($form_state['values']['mukurtu_frontpage_sections']) + 1;
  }

  return $mukurtu_frontpage_values;
}
*/

/** 
 * AHAH callback.
 */ 
/*
function mukurtu_frontpage_ahah() {
  $form_state = array('storage' => NULL, 'rebuild' => TRUE);
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form['#post'] = $_POST;
  $form['#redirect'] = FALSE;
  $form['#programmed'] = FALSE;
  $form_state['post'] = $_POST;
  drupal_process_form($form_id, $form, $form_state);
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);
  $mukurtu_frontpage_form = $form['mukurtu_frontpage_settings']['mukurtu_frontpage_sections'];
  unset($mukurtu_frontpage_form['#prefix'], $mukurtu_frontpage_form['#suffix']); // Prevent duplicate wrappers.
  $javascript = drupal_add_js(NULL, NULL, 'header');
  drupal_json(array(
    'status'   => TRUE,
    'data'     => theme('status_messages') . drupal_render($mukurtu_frontpage_form),
    'settings' => call_user_func_array('array_merge_recursive', $javascript['setting']),
  ));
}
*/

function mukurtu_frontpage_content() {

  global $base_url;
  $output = '';
  
  return $output;
}

// A lightweight frontpage singlepage app - with a little bit of database integration for content-editing purposes.
function mukurtu_frontpage_preprocess_page(&$vars){
  if($vars['is_front']) {
    global $base_path;
    drupal_add_js(array('mukurtu_frontpage' => array('menu_element' => variable_get('mukurtu_frontpage_menu', '#main-menu'), 'base_path' => $base_path)), 'setting');
    drupal_add_js(drupal_get_path('module', 'mukurtu_frontpage') . '/js/mukurtu_frontpage.js');

    if (module_exists('libraries')) {
      $underscore_path = libraries_get_path('underscore');
      $bootstrap_path = libraries_get_path('bootstrap');
      drupal_add_js($underscore_path . '/underscore-min.js');
      drupal_add_js($bootstrap_path . '/js/bootstrap.js');
      drupal_add_css($bootstrap_path . '/css/bootstrap.min.css');
      drupal_add_css($bootstrap_path . '/css/bootstrap-responsive.min.css');
      drupal_add_css($bootstrap_path . '/css/bootstrap-responsive.min.css');
      drupal_add_css(drupal_get_path('module', 'mukurtu_frontpage') . '/css/mukurtu_frontpage.css');
      drupal_add_js(drupal_get_path('module', 'jcarousel') . '/js/jquery.jcarousel.min.js');
    }
  
    $vars['frontpage'] = array();    

    // @TODO these will be linked to a form -- and will be able to add some more as necessary. Hard-coding for now.
    $vars['frontpage']['page_items'] = mukurtu_frontpage_content_load();

    foreach($vars['frontpage']['page_items']['sections'] as $item) {
      if($item['jsondata']) {      
        $json_path = $item['jsondata'];
        // Load json data.
        drupal_add_js('mukurtu_frontpage.query("' . $json_path . '", mukurtu_frontpage.loadData, "' . $item['anchor'] .'")',  array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
      }
    }
 
  }
}

function mukurtu_frontpage_theme_registry_alter(&$theme_registry) {
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'mukurtu_theme', MUKURTU_FRONTPAGE);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);

  // A list of templates the module will provide templates for
  $hooks = array('page');
  foreach ($hooks as $h) {
    // Add the key 'theme paths' if it doesn't exist in this theme's registry
    if (!isset($theme_registry[$h]['theme paths'])) {
      $theme_registry[$h]['theme paths'] = array();
    }

    //Shift this module's directory to the top of the theme path list 
    if(is_array($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      if ($first_element) {
        array_unshift($theme_registry[$h]['theme paths'], $first_element, MUKURTU_FRONTPAGE);
      } else {
        array_unshift($theme_registry[$h]['theme paths'], MUKURTU_FRONTPAGE);
      }
    }
  }
}
